### ISSUE TITLE
Delete all multi part rar archive files after extraction

### ISSUE THREAD

**Issue by ninjamode** [aonez/Keka#115]
At the moment Keka will only delete the first part of a multi part rar archive if the option _Move to trash after extraction_ has been selected. Should delete all parts after successful extraction.

**Comment by aonez** [comment]
Please try the latest beta. This should be fixed #8.

**Comment by ninjamode** [comment]
Yes it's fixed in the beta. Should have checked there first, thank you

**Comment by hismum** [comment]
This issue is not fixed it still happens in Version 1.0.15 (1804)

**Comment by aonez** [comment]
@hismum this is fixed in 1.1.0 betas.

**Comment by hismum** [comment]
Will it be added to the full version? It seems odd that it was fixed in the beta back in November but new full versions are being released without the fix?
