### ISSUE TITLE
[BUG] Default extraction location selector not working

### ISSUE THREAD

**Issue by giternal** [aonez/Keka#1525]
### Configuration
- Keka version:  1.4.4 (5475)
- macOS 10.15.0
- 
### Describe the bug
I cannot assign a folder to export files, nothing happening on selecting the relevant item

### To Reproduce
1. Go to Settings/Unarchieving
2. Click on 'Unarchieve files'
3. Scroll down to 'Select Folder ...'
4. Nothing happening - I cannot assign a folder to export

**Comment by aonez** [comment]
Thanks a lot for the feedback @giternal!

Already fixed this for the next release. This build is already fixed:
https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.4.5.r5485.7z

**Comment by keif** [comment]
I'm running 1.4.5 at the moment and the issue is still occurring for me.

Selecting Enable Home/Volume/Custom access doesn't do anything, and any multi-part extraction asks for "all volumes" but won't work since it won't save that I've given it permission.

**Comment by delize** [comment]
Can confirm, also running 1.4.5 from above, on macOS 15.0.1 and I repeatedly am stuck at the extraction screen even though Keka has both Full Disk Access, and access to Home/External Volumes. 

If I try and extract to the /tmp folder or /Users/Shared, the Extract button is grayed out. 
If I try and extract to my Documents folder or the same folder as the archive, I just get stuck in a loop.

**Comment by aonez** [comment]
Please don't mix issues. The original issue is about Extraction - Extraction location dialog not working. I've created this issue https://github.com/aonez/Keka/issues/1529 for you @keif & @delize.
